### ISSUE TITLE
Usage seems unclear

### ISSUE THREAD

**Issue by jdblack** [datasift/php_webdriver#2]
I was able to get php_webdriver installed by performing the following:

pear channel-discover pear.phix-project.org
pear channel-discover datasift.github.io/pear
pear install --alldeps DataSift/webdriver

I'm not quite clear on how to actually include php_webdriver, though.  I'm pretty sure I"m not including things correctly. I've gotten as far as the following:

<?php
namespace DataSift\WebDriver;

require 'DataSift/WebDriver/WebDriverBase.php';
require 'DataSift/WebDriver/WebDriverClient.php';

$driver = new WebDriverClient;
$session = $driver->newSession();
?>

Which bombs out with: 

PHP Fatal error:  Class 'DataSift\WebDriver\E5xx_WebDriverCurlException' not found in /usr/share/php/DataSift/WebDriver/WebDriverBase.php on line 218
PHP Stack trace:
PHP   1. {main}() /home/jblack/test.php:0
PHP   2. DataSift\WebDriver\WebDriverClient->newSession() /home/jblack/test.php:10
PHP   3. DataSift\WebDriver\WebDriverBase->curl() /usr/share/php/DataSift/WebDriver/WebDriverClient.php:74

**Comment by stuartherbert** [comment]
H @jdblack 

Can I recommend switching to Composer? This package is 'datasift/webdriver' on there.

PEAR is pretty much dead these days, and Composer is now the de facto standard for the PHP community. I'm no longer supporting PEAR in any of my projects.

Best regards,
Stu
--
